In [1]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
# Load the dataset
dataset = pd.read_csv("Data/ev_charging_patterns.csv")
dataset

User ID Vehicle Model  Battery Capacity (kWh) Charging Station ID  \
0        User_1        BMW i3              108.463007         Station_391   
1        User_2  Hyundai Kona              100.000000         Station_428   
2        User_3    Chevy Bolt               75.000000         Station_181   
3        User_4  Hyundai Kona               50.000000         Station_327   
4        User_5  Hyundai Kona               50.000000         Station_108   
...         ...           ...                     ...                 ...   
1315  User_1316   Nissan Leaf              100.000000          Station_57   
1316  User_1317        BMW i3              100.000000          Station_40   
1317  User_1318   Nissan Leaf              100.000000         Station_374   
1318  User_1319    Chevy Bolt               85.000000         Station_336   
1319  User_1320   Nissan Leaf              120.447195         Station_128   

     Charging Station Location Charging Start Time Charging End Time  \
0                      Houston     01/01/2024 0:00   01/01/2024 0:39   
1                San Francisco     01/01/2024 1:00   01/01/2024 3:01   
2                San Francisco     01/01/2024 2:00   01/01/2024 4:48   
3                      Houston     01/01/2024 3:00   01/01/2024 6:42   
4                  Los Angeles     01/01/2024 4:00   01/01/2024 5:46   
...                        ...                 ...               ...   
1315                  New York    24/02/2024 19:00  24/02/2024 20:30   
1316                  New York    24/02/2024 20:00  24/02/2024 20:44   
1317                  New York    24/02/2024 21:00  24/02/2024 23:03   
1318             San Francisco    24/02/2024 22:00  24/02/2024 23:20   
1319               Los Angeles    24/02/2024 23:00  24/02/2024 23:56   

      Energy Consumed (kWh)  Charging Duration (hours)  Charging Rate (kW)  \
0                 60.712346                   0.591363           36.389181   
1                 12.339275                   3.133652           30.677735   
2                 19.128876                   2.452653           27.513593   
3                 79.457824                   1.266431           32.882870   
4                 19.629104                   2.019765           10.215712   
...                     ...                        ...                 ...   
1315              42.011654                   1.426444            5.895475   
1316              68.185853                   3.238212           18.388012   
1317              18.895102                   3.267122           45.482066   
1318              13.756251                   2.754527           38.148183   
1319              63.652570                   3.740970           33.704226   

      Charging Cost (USD) Time of Day Day of Week  State of Charge (Start %)  \
0               13.087717     Evening     Tuesday                  29.371576   
1               21.128448     Morning      Monday                  10.115778   
2               35.667270     Morning    Thursday                   6.854604   
3               13.036239     Evening    Saturday                  83.120003   
4               10.161471     Morning    Saturday                  54.258950   
...                   ...         ...         ...                        ...   
1315            22.081164     Evening      Sunday                  39.204102   
1316             5.067806     Evening     Tuesday                  31.456375   
1317            37.255002     Evening     Tuesday                  71.903081   
1318            39.046146   Afternoon      Sunday                  76.187997   
1319            10.863674     Evening      Monday                  59.338076   

      State of Charge (End %)  Distance Driven (since last charge) (km)  \
0                   86.119962                                293.602111   
1                   84.664344                                112.112804   
2                   69.917615                                 71.799253   
3                   

In [3]:
# Show the first few rows of the dataset
dataset.head()

User ID Vehicle Model  Battery Capacity (kWh) Charging Station ID  \
0  User_1        BMW i3              108.463007         Station_391   
1  User_2  Hyundai Kona              100.000000         Station_428   
2  User_3    Chevy Bolt               75.000000         Station_181   
3  User_4  Hyundai Kona               50.000000         Station_327   
4  User_5  Hyundai Kona               50.000000         Station_108   

  Charging Station Location Charging Start Time Charging End Time  \
0                   Houston     01/01/2024 0:00   01/01/2024 0:39   
1             San Francisco     01/01/2024 1:00   01/01/2024 3:01   
2             San Francisco     01/01/2024 2:00   01/01/2024 4:48   
3                   Houston     01/01/2024 3:00   01/01/2024 6:42   
4               Los Angeles     01/01/2024 4:00   01/01/2024 5:46   

   Energy Consumed (kWh)  Charging Duration (hours)  Charging Rate (kW)  \
0              60.712346                   0.591363           36.389181   
1              12.339275                   3.133652           30.677735   
2              19.128876                   2.452653           27.513593   
3              79.457824                   1.266431           32.882870   
4              19.629104                   2.019765           10.215712   

   Charging Cost (USD) Time of Day Day of Week  State of Charge (Start %)  \
0            13.087717     Evening     Tuesday                  29.371576   
1            21.128448     Morning      Monday                  10.115778   
2            35.667270     Morning    Thursday                   6.854604   
3            13.036239     Evening    Saturday                  83.120003   
4            10.161471     Morning    Saturday                  54.258950   

   State of Charge (End %)  Distance Driven (since last charge) (km)  \
0                86.119962                                293.602111   
1                84.664344                                112.112804   
2                69.917615                                 71.799253   
3                99.624328                                199.577785   
4                63.743786                                203.661847   

   Temperature (°C)  Vehicle Age (years)     Charger Type  \
0         27.947953                  2.0  DC Fast Charger   
1         14.311026                  3.0          Level 1   
2         21.002002                  2.0          Level 2   
3         38.316313                  1.0          Level 1   
4         -7.834199                  1.0          Level 1   

                User Type  
0                Commuter  
1           Casual Driver  
2                Commuter  
3  Long-Distance Traveler  
4  Long-Distance Traveler

In [24]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load the dataset
dataset = load_iris()
X = dataset.data  # Feature matrix
y = dataset.target  # Target variable (labels)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [26]:
# Logistic Regression Model
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

# Predictions
y_pred_logreg = logreg.predict(X_test)

# Evaluate
logreg_accuracy = accuracy_score(y_test, y_pred_logreg)
print(f"Logistic Regression Accuracy: {logreg_accuracy:.2f}")

Logistic Regression Accuracy: 1.00


In [28]:
from sklearn.neighbors import KNeighborsClassifier

# KNN Model
knn = KNeighborsClassifier(n_neighbors=5)  # You can adjust n_neighbors as needed
knn.fit(X_train, y_train)

# Predictions
y_pred_knn = knn.predict(X_test)

# Evaluate
knn_accuracy = accuracy_score(y_test, y_pred_knn)
print(f"KNN Accuracy: {knn_accuracy:.2f}")


KNN Accuracy: 1.00


In [30]:
from sklearn.naive_bayes import GaussianNB

# Naive Bayes Model
nb = GaussianNB()
nb.fit(X_train, y_train)

# Predictions
y_pred_nb = nb.predict(X_test)

# Evaluate
nb_accuracy = accuracy_score(y_test, y_pred_nb)
print(f"Naïve Bayes Accuracy: {nb_accuracy:.2f}")


Naïve Bayes Accuracy: 0.98


In [32]:
from sklearn.tree import DecisionTreeClassifier

# Decision Tree Model
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

# Predictions
y_pred_dt = dt.predict(X_test)

# Evaluate
dt_accuracy = accuracy_score(y_test, y_pred_dt)
print(f"Decision Tree Accuracy: {dt_accuracy:.2f}")


Decision Tree Accuracy: 1.00


In [52]:
dataset = load_iris()  # Loading Iris dataset
df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)  # Convert to DataFrame

In [36]:
# Define features (X) and target (y)
X = df  # Features are the entire DataFrame
y = dataset.target  # Target is the 'target' from the dataset

In [38]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Verify the shapes of the splits
print(X_train.shape, X_test.shape)


(120, 4) (30, 4)


In [40]:

# Initialize the classifier
model = LogisticRegression(max_iter=200)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")


Accuracy: 1.0
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [42]:
# Define models
models = {
    'Logistic Regression': LogisticRegression(max_iter=200),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'SVC': SVC(),
    'k-NN': KNeighborsClassifier(),
    'Naive Bayes': GaussianNB()
}

In [54]:

# Evaluate each model
for model_name, model in models.items():
    print(f"Evaluating {model_name}:")
    
    # Train the model
    model.fit(X_train, y_train)
    
    # Make predictions
    y_pred = model.predict(X_test)
    
    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for {model_name}:\n{cm}")
    
    # Accuracy Score
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy for {model_name}: {accuracy:.4f}\n")

Evaluating Logistic Regression:
Confusion Matrix for Logistic Regression:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy for Logistic Regression: 1.0000

Evaluating Decision Tree:
Confusion Matrix for Decision Tree:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy for Decision Tree: 1.0000

Evaluating Random Forest:
Confusion Matrix for Random Forest:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy for Random Forest: 1.0000

Evaluating SVC:
Confusion Matrix for SVC:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy for SVC: 1.0000

Evaluating k-NN:
Confusion Matrix for k-NN:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy for k-NN: 1.0000

Evaluating Naive Bayes:
Confusion Matrix for Naive Bayes:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy for Naive Bayes: 1.0000



In [46]:
#17.	Predict the dependent variable by using best-fit classifier.

In [48]:
# Initialize classifiers
classifiers = {
    'RandomForest': RandomForestClassifier(),
    'SVM': SVC(),
    'DecisionTree': DecisionTreeClassifier(),
    'LogisticRegression': LogisticRegression()
}

In [50]:

# Train and evaluate each classifier
for name, clf in classifiers.items():
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(f"Model: {name}")
    print(classification_report(y_test, y_pred))
    

Model: RandomForest
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Model: SVM
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Model: DecisionTree
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00 